### ISSUE TITLE
Add ability to be launched via external commands

### ISSUE THREAD

**Issue by WingofaGriffin** [PhilPotter/MasterEmu#22]
Being able to launch apps via a command in an app such as Daijisho would be useful for organizing app libraries. See https://github.com/magneticchen/Daijishou/issues/151

**Comment by PhilPotter** [comment]
Sorry it has taken me so long to reply. I'm not going to be adding this for now, as the project is somewhat in maintenance mode. I do plan to come back to it at some point though.
