### ISSUE TITLE
bios

### ISSUE THREAD

**Issue by soundsnow** [PhilPotter/MasterEmu#8]
some games require a BIOS file to load
if not, blackscreen

Sonic's Edusoft (Unknown) (Proto).sms
gg and sms bios

**Comment by PhilPotter** [comment]
So this game apparently doesn't require an actual BIOS, just that vertical interrupt bit be set on boot. I tested this change and it indeed allows the game to boot. Further research needed on my part to determine if this affects other games negatively.
