### ISSUE TITLE
Lightgun, Paddle, Sports Pad

### ISSUE THREAD

**Issue by soundsnow** [PhilPotter/MasterEmu#9]
Sega Master System
[Light Phaser](https://segaretro.org/Light_Phaser)

    Assault City (also compatible with standard control pad)
    Gangster Town
    Laser Ghost (also compatible with standard control pad)
    Marksman Shooting
    Missile Defense 3-D
    Operation: Wolf
    Rambo III
    Rescue Mission
    Safari Hunt
    Shooting Gallery
    Space Gun
    Trap Shooting
    Wanted!

[Paddle Control](https://segaretro.org/Paddle_Control)

    BMX Trial: Alex Kidd (required)
    Galactic Protector (required)
    Megumi Rescue (required)
    OutRun (optional)
    OutRun 3D (optional)
    Super Racing (optional)
    Woody Pop: Shinjinrui no Block Kuzugi (required)

[Sports Pad](https://segaretro.org/Sports_Pad)

    Great Ice Hockey
    Sports Pad Football
    Sports Pad Soccer

SG-1000
[Terebi Oekaki](https://segaretro.org/Terebi_Oekaki)
[Sega Graphic Board](https://segaretro.org/Sega_Graphic_Board)

**Comment by PhilPotter** [comment]
Thank you for registering the issue, but I'm unlikely to be able to support this on my own given the limited time available to me. I welcome pull requests though by all means.
